### ISSUE TITLE
Feature request: Remember the last opened file, and automatically open it on the next launch

### ISSUE THREAD

**Issue by JaneSmith** [johannesjh/fava-gtk#5]
Hello. First of all, great work on this Flatpak package. It's such a huge help having this finally packaged as a modern Flatpak app.

I know this is still early days, but I have a feature request. As the title says, I would like `fava-gtk` to remember the last Beancount file that I had open, so that when I next open the app, it can just automatically re-open my Beancount ledger.

I don't know about everyone else, but personally I just have one main file that I keep all my records in. I would imagine most people would be setup like this too, but maybe I'm wrong. Currently, I have to navigate to and open my Beancount file every time I launch the app. It would be a big time-saver if it would open it for me automatically.

**Comment by johannesjh** [comment]
Hi, thank you for the suggestion, yes I agree, this would make using fava-gtk more convenient. Would you want to implement this? I may also find time for this in the next few weeks or so.

Quick research: The [GTK RecentManager](https://athenajc.gitbooks.io/python-gtk-3-api/content/gtk-group/gtkrecentmanager.html) can save which file(s) were previously opened, and can provide a list of recently opened files to the application. There also exist some GUI widgets based on this functionality, e.g., a [GTK Recent Chooser Menu Widget](https://athenajc.gitbooks.io/python-gtk-3-api/content/gtk-group/gtkrecentchoosermenu.html).

UI Design: I think that something similar to gedit would work well, see the following screenshot.

![Screenshot from 2021-02-27 18-21-19](https://user-images.githubusercontent.com/581188/109394717-b2c77180-7928-11eb-9231-4a8fdaeb3d07.png)

**Comment by johannesjh** [comment]
Hi Jane, I added a dropdown menu that allows to quickly open a recently used beancount file. Some notes regarding the implementation:

* The application still shows the placeholder screen when it starts. I intentionally left the start sceen as it was before because my beancount files are on encrypted drives, and I did not want to spend too much time handling errors when previously opened files are not available anymore). 
* I added a new dropdown menu (next to the "open" button). This makes it much quicker to open a recently-used file. 
* You may find that the dropdown menu is initially empty... in my experience, this happened due to flatpak sandboxing. Once I started opening beancount files using the fava app, the dropdown menu got populated with those files. The dropdown menu should only show files that are available in the file system. This is a feature of the GTK RecentChooserMenu widget), and it seems to work correctly based on my limited experience. 

The changes are on the master branch now. May I ask you to please give them a try and see if they work fine for you? 

Thank you and best regards, 
Johannes

**Comment by JaneSmith** [comment]
Hello again. Sorry for taking a while to get back to you. I've tried out your changes and it's definitely better than before. It seems to work without any issues, at least as far as I can tell, and it does make it quicker to load up my file. Thanks a lot for doing that.

That said, I'd still really prefer if Fava-GTK could automatically open my most recent file — without the step of having to use the dropdown menu. As I said initially, I only have one Beancount file anyway, so I would always just be opening up the same file every time. I might be wrong as I'm just making an assumption, but I think most people would probably only be using one file too? Generally we'd use Fava to track our own finances, right? So we'd have "MyFinances.beancount" or something similar...

Now that Fava-GTK has this (great!) new feature and tracks recently used files, would it be possible to take it a step further? And have an option to automatically open the most recent file when Fava-GTK starts up?

**Comment by johannesjh** [comment]
Thank you for testing and for suggesting the additional ui change. 

This is implemented now. In other words, the most recently used file is opened automatically when the application starts. (commit 84207be47a757e6e0938a9f90b61c0db5ecd9c1e). Can you let me know again if it works for you? thanks.

Implementation notes for future reference: There were quite a few edge cases to be handled. For example, the most recent file may have been deleted or renamed in the meantime, or it may temporarily have become unavailable because a volume was unmounted. User expectations may differ in such situations. The current implementation works like this: 
* On startup, the application opens the same file that would be shown as first menu entry. This is the most recent beancount file that currently exists in the filesystem. 
* To avoid confusion about which file was opened automatically, the filename is now displayed in the window's headerbar.
* Each time the user pops down the recent-files-menu, the menu contents are freshly filtered in order to exclude files that have gone missing in the meantime. This required a workaround, but it is is a much nicer solution, much better than offering the menu item only to show an error dialog when it is chosen.

**Comment by johannesjh** [comment]
UPDATE:
I think I might review/revise yesterday's implementation. It may be the case that other GNOME applications (like gedit) add recent entries when they open beancount files. It would be confusing if Fava-Gtk would consequently open a file only because it was recently opened in gedit. I still need to test if this is a problem or not. The behavior seems to be inconsistent depending on flatpak packaging. 

I think that user expectations would be better met by persisting the file name each time a window is closed. I could probably use a GTK helper class to persist this setting. When the application starts, it would try to re-open this file. In case of error, e.g., if the file does not exist in the filesystem anymore, the start screen would be shown.

**Comment by JaneSmith** [comment]
I've tested the changes you made. As far as I can tell, it works great. I haven't encountered any issues. If I open files with Gedit (Flatpak), they don't show up in Fava-GTK, even if they're .beancount files.

I don't know if the implementation could be improved or not, but from my perspective it's already a big improvement and makes the application so much more convenient. A big thanks to you for working on this!

**Comment by johannesjh** [comment]
I refactored the mechanism how application state is stored and restored. A json file persists which file (if any) was opened when the application quit. When the application starts, it tries to re-open that file. The mechanism is now independent from GTK's recent items. As a benefit, this avoids interference with other applications that may also open beancount files. The dropdown menu still uses GTK's global list of recent items.
