### ISSUE TITLE
Fava Investor / Is it possible to use Fava plugins?

### ISSUE THREAD

**Issue by ChrisTucker2000** [johannesjh/fava-gtk#6]
I'm looking to use the [Fava Investor](https://github.com/redstreet/fava_investor) plugin. Is it possible to use this together with Fava GTK?

If it's currently not possible, then what's going to be the plan for that going forward? Could popular or useful plugins just be bundled with the app? Maybe they could be toggleable in a preferences window, similar to what GNOME Text Editor (Gedit) does? Or otherwise, is it possible to have them as Flatpak extensions? That would probably be the better way... but I don't know enough about Flatpak to know if it's easily done or not.

**Comment by johannesjh** [comment]
Hi, yes I can see the need. You can send a pull request that adds fava-investor to [`requirements/req-extras.in`](https://github.com/johannesjh/fava-gtk/blob/main/requirements/req-extras.in).

Some more thoughts around this topic:

* Pragmatic approach: What would always work is that you can install the fava-gtk python package in a virtualenv. Then you are free to install whatever additional packages you like. Simply add them to [`requirements/req-extras.in`](https://github.com/johannesjh/fava-gtk/blob/main/requirements/req-extras.in). You can also build flatpak packages from that. In fact, I have already added additional packages that I needed in `req-extras.in`... I even added smart_importer because I needed/wanted it, despite its heavy dependencies on scikit-learn and numpy. I am aware that this approach does not scale well with regard to the number of extra packages. Also each additional package adds maintenance burden. But for the meantime, I guess a curated list of packages that we are interested in using personally (and in maintaining as part of fava-gtk) looks feasible and pragmatic to me. Hence the invitation to send a pull request.

* Thoughts about a suitable long-term solution: I am not sure about the plugin mechanism, whether we should build it at all, and also how it can be built:
  * fava-gtk could load code from the host's file system. I think this would work - in fact, the import configuration works just like that. But architecturally, this is the opposite of what all the new sandboxing package formats want to achieve. Also, it would make it quite likely that code inside and outside the sandbox to does not work together... looks like calling for trouble to me.
  * Alternatively, fava-gtk could rely on extension mechanisms as provided by flatpak and other package formats like snap and appimage. I read this [blog post explaining how flatpak extensions work](https://blog.tingping.se/2018/03/18/flatpaking-plugins.html). But I am not too keen on using such mechanisms because they are likely to be different for each package format.
  * I suggest we should take these steps slowly, i.e., wait before we start with this. Let's first get the main application to work smoothly, let's gather some practical experience with it, and see where we go from there.

**Comment by ChrisTucker2000** [comment]
Thanks a lot for your reply and all your thoughts. For now, I've gone ahead and added pull request #7. As far as I can tell it works fine on my end.

**Comment by johannesjh** [comment]
Thank you for the pull request. I built your branch, gave it a try, seemed to work fine (i.e., the "investor" menu item appeared once I added `2000-01-01 custom "fava-extension" "fava_investor" "{}"` to an example beancount file), merged the changes.
